// Generated by LiveScript 1.3.1
(function(){
  var util, log_with_status, log_error, log_success, exit_if_error, exit_with_error, exit_with_success, out$ = typeof exports != 'undefined' && exports || this;
  util = require('util');
  out$.log_with_status = log_with_status = function(message, status){
    var data;
    if (message == null) {
      message = '';
    }
    if (message.message != null) {
      data = message;
    } else {
      data = {
        message: message
      };
    }
    data.status = status;
    return console.log(util.inspect(data, {
      depth: null
    }));
  };
  out$.log_error = log_error = function(message){
    return log_with_status(message, 'error');
  };
  out$.log_success = log_success = function(message){
    return log_with_status(message, 'success');
  };
  out$.exit_if_error = exit_if_error = function(message){
    if (message == null) {
      return;
    }
    return exit_with_error(message);
  };
  out$.exit_with_error = exit_with_error = function(message){
    log_error(message);
    return process.exit(1);
  };
  out$.exit_with_success = exit_with_success = function(message){
    log_success(message);
    return process.exit(0);
  };
}).call(this);
